"use strict";

// Wave EGRESS-TOGGLE — fleet-wide egress family toggle for the node-agent.
//
// Rewrites the leading 3proxy egress flag in EVERY 3proxy config on this node
// and restarts the affected 3proxy instances, so the orchestrator can flip the
// whole fleet between dual-stack (-64, v4+v6 egress) and ipv6-only (-6) with a
// single button.
//
// 3proxy config lines this touches (generated by soft/generator —
// proxyyy_automated.sh: `proxy_startup_depending_on_type="socks $mode_flag -a"`
// / `"proxy $mode_flag -n -a"`, $mode_flag ∈ {-64, -6}):
//
//   dualstack:  'socks -64 -a -p... -i... -e...'
//               'proxy -64 -n -a -p... -i... -e...'
//   ipv6_only:  'socks -6 -a -p... -i... -e...'
//               'proxy -6 -n -a -p... -i... -e...'
//
// Only the LEADING flag on a socks/proxy startup line is rewritten. The rewrite
// is anchored (`^\s*(socks|proxy)\s+`) and the flag match is space-delimited so
// '-6 ' can never partially match inside '-64 '. Re-applying the same mode is a
// no-op (idempotent): a config already in the target mode is left byte-for-byte
// unchanged and its proxy is NOT restarted.

const fs = require("fs");
const fsp = require("fs/promises");
const path = require("path");
const { spawn } = require("child_process");
const proxySpawn = require("./proxy_spawn.js");
const { withProcessLock } = require("./process_lock.js");

const PROXY_ROOT = path.normalize(process.env.NODE_AGENT_PROXY_ROOT || "/opt/netrun/proxyserver");
const PROXY_CFG_DIR = path.join(PROXY_ROOT, "3proxy");
// Persisted current egress mode. The generation contract (server.js) reads this
// so the required ipv6 policy FOLLOWS the toggle — making the egress switch
// truly bidirectional (flipping existing proxies AND gating new generation).
const EGRESS_MODE_STATE_PATH = path.join(PROXY_ROOT, "egress_mode.state");
const PROXY_BIN = path.join(PROXY_ROOT, "3proxy", "bin", "3proxy");

const VALID_MODES = new Set(["ipv6_only", "dualstack"]);
// Egress family flag per mode. dualstack = -64 (v4+v6), ipv6_only = -6.
const FLAG_FOR_MODE = { dualstack: "-64", ipv6_only: "-6" };

// 3proxy treats SIGTERM as GRACEFUL (it keeps in-flight connections alive and
// HOLDS the listening socket until they drain). Mirror accounting.disablePort:
// after SIGTERM wait this grace, then SIGKILL survivors so the -p<port> socket
// is actually free before we respawn (same lesson as the metering SIGKILL fix).
const EGRESS_RESTART_GRACE_MS = Number(process.env.EGRESS_RESTART_GRACE_MS) || 2000;
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

class EgressModeError extends Error {
  constructor(message, detail) {
    super(message);
    this.name = "EgressModeError";
    this.code = "EGRESS_MODE_ERROR";
    this.detail = detail;
  }
}

// Anchored match of a 3proxy startup line's leading egress flag. Group 1 is the
// service keyword (socks|proxy), group 2 the leading-whitespace-preserving
// prefix already captured, group 3 the flag. We rebuild the line so ONLY the
// flag token changes and the trailing args are untouched.
//   ^(\s*)(socks|proxy)(\s+)(-64|-6)(\s)
// The trailing (\s) is required so '-6' is never matched as a prefix of '-64':
// '-64 ' has a space after '4', '-6' inside it is followed by '4' (no space),
// so the alternation '-64|-6' with a mandatory following \s only ever matches a
// complete, space-delimited flag token.
const STARTUP_FLAG_RE = /^(\s*)(socks|proxy)(\s+)(-64|-6)(\s)/;

function flagForMode(mode) {
  const flag = FLAG_FOR_MODE[mode];
  if (!flag) {
    throw new EgressModeError("invalid_mode", String(mode));
  }
  return flag;
}

// Persist the current egress mode atomically (write tmp + rename). Never throws:
// the cfg rewrite/restart has already happened by the time we record state, so a
// state-write failure is surfaced to the caller's error list, not raised.
function persistEgressModeState(mode) {
  const tmp = `${EGRESS_MODE_STATE_PATH}.tmp`;
  fs.writeFileSync(tmp, `${mode}\n`, "utf-8");
  fs.renameSync(tmp, EGRESS_MODE_STATE_PATH);
}

// Read the persisted egress mode. Returns the trimmed mode string when it is a
// known VALID_MODES value, else null (missing / unreadable / malformed file).
// Sync + cheap + never throws — safe to call on the generate path.
function readEgressModeState() {
  try {
    const raw = fs.readFileSync(EGRESS_MODE_STATE_PATH, "utf-8").trim();
    return VALID_MODES.has(raw) ? raw : null;
  } catch {
    return null;
  }
}

// Rewrite the leading egress flag on every socks/proxy startup line of one
// config's text. Returns { text, changed } — `changed` is false when the text
// was already in the target mode (idempotent no-op). Pure string function so it
// is trivially unit-testable without the filesystem or a Linux proxy stack.
function rewriteConfigText(text, mode) {
  const targetFlag = flagForMode(mode);
  let changed = false;
  // Preserve the original newline style (the generator writes \n) — split on \n
  // and keep a trailing-newline-aware join so we don't add/drop a final newline.
  const lines = text.split("\n");
  const out = lines.map((line) => {
    const m = STARTUP_FLAG_RE.exec(line);
    if (!m) return line;
    const currentFlag = m[4];
    if (currentFlag === targetFlag) return line; // already target — no-op
    changed = true;
    // Replace ONLY the leading flag token; the rest of the line is preserved.
    return line.replace(STARTUP_FLAG_RE, `$1$2$3${targetFlag}$5`);
  });
  return { text: out.join("\n"), changed };
}

async function listConfigPaths() {
  let entries;
  try {
    entries = await fsp.readdir(PROXY_CFG_DIR, { withFileTypes: true });
  } catch (err) {
    if (err && err.code === "ENOENT") {
      // No proxy config dir yet (fresh node / nothing provisioned) — zero
      // configs is a legitimate, non-error state.
      return [];
    }
    throw new EgressModeError("cfg_dir_read_failed", String((err && err.message) || err));
  }
  return entries
    .filter((e) => e.isFile() && /^3proxy_\d+\.cfg$/.test(e.name))
    .map((e) => path.join(PROXY_CFG_DIR, e.name))
    .sort();
}

function execFind(cmd, args, { timeoutMs = 5000 } = {}) {
  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";
    let settled = false;
    let child;
    try {
      child = spawn(cmd, args, { stdio: ["ignore", "pipe", "pipe"] });
    } catch (err) {
      resolve({ code: -1, stdout: "", stderr: String((err && err.message) || err) });
      return;
    }
    const timer = setTimeout(() => {
      if (settled) return;
      try { child.kill("SIGKILL"); } catch {}
    }, timeoutMs);
    child.stdout.on("data", (d) => { stdout += d.toString("utf-8"); });
    child.stderr.on("data", (d) => { stderr += d.toString("utf-8"); });
    child.on("error", (err) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({ code: -1, stdout, stderr: stderr || String((err && err.message) || err) });
    });
    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({ code: typeof code === "number" ? code : -1, stdout, stderr });
    });
  });
}

// Find the running 3proxy pids for a specific config file. Mirrors
// accounting.js findRunningPids but keys on the cfg BASENAME so it works for
// any 3proxy_<id>.cfg (the cfg filename id is the instance/start-port, which is
// what 3proxy was launched with — see soft/generator/proxyyy_automated.sh:904
// `nohup .../bin/3proxy <cfg> &`).
async function findPidsForCfg(cfgPath) {
  const base = path.basename(cfgPath);
  const result = await execFind("pgrep", ["-f", base]);
  if (result.code === 0) {
    return result.stdout
      .split(/\s+/)
      .map((s) => s.trim())
      .filter((s) => /^\d+$/.test(s))
      .map(Number);
  }
  if (result.code === 1) return []; // pgrep: no match
  throw new EgressModeError("pgrep_failed", result.stderr || `exit ${result.code}`);
}

// Restart the 3proxy serving one config: kill any running pids for that exact
// cfg, then re-spawn `3proxy <cfg>` detached — the SAME launch shape the node
// already uses (accounting.enablePort + generator nohup line). 3proxy re-reads
// the (now rewritten) config on (re)start, so the new egress flag takes effect.
async function restartCfg(cfgPath) {
  const pids = await findPidsForCfg(cfgPath);
  for (const pid of pids) {
    try {
      process.kill(pid, "SIGTERM");
    } catch (err) {
      if (err && err.code !== "ESRCH") {
        throw new EgressModeError("kill_failed", String((err && err.message) || err));
      }
    }
  }
  // SIGTERM is graceful for 3proxy → it can keep the old process (and its
  // listening socket) alive on a busy port, so the respawn below would fail to
  // bind and the egress flip would silently not take effect. After a short
  // grace, re-resolve and SIGKILL any survivor for this exact cfg (re-resolving
  // avoids hitting a recycled PID) so the socket is guaranteed free on respawn.
  if (pids.length) {
    await sleep(EGRESS_RESTART_GRACE_MS);
    let survivors;
    try {
      survivors = await findPidsForCfg(cfgPath);
    } catch {
      survivors = pids; // re-resolve failed — fall back to the signalled set
    }
    for (const pid of survivors) {
      try {
        process.kill(pid, "SIGKILL");
      } catch (err) {
        if (err && err.code !== "ESRCH") {
          throw new EgressModeError("kill_failed", String((err && err.message) || err));
        }
      }
    }
  }
  // Audit RES-11 — the respawn goes through the node's spawn helper (own
  // systemd scope; the direct detached start where the helper is absent).
  let res;
  try {
    res = await proxySpawn.spawn3proxyCfg(cfgPath, { bin: PROXY_BIN });
  } catch (err) {
    if (err && err.code === "BINARY_MISSING") throw new EgressModeError("3proxy_binary_missing", PROXY_BIN);
    throw new EgressModeError("3proxy_spawn_failed", String((err && err.message) || err));
  }
  if (!res.ok) throw new EgressModeError("3proxy_spawn_failed", res.detail || res.outcome);
  return { restarted: true, killed: pids };
}

// Apply an egress mode across every 3proxy config on this node:
//   1. rewrite the leading socks/proxy egress flag in each cfg (idempotent),
//   2. restart only the configs whose flag actually changed.
// Returns { mode, cfgs_rewritten, restarted } per the node-agent contract.
async function applyEgressMode(mode) {
  if (!VALID_MODES.has(mode)) {
    throw new EgressModeError("invalid_mode", String(mode));
  }
  const cfgPaths = await listConfigPaths();
  let cfgsRewritten = 0;
  const restartErrors = [];

  for (const cfgPath of cfgPaths) {
    let original;
    try {
      original = await fsp.readFile(cfgPath, "utf-8");
    } catch (err) {
      restartErrors.push({ cfg: path.basename(cfgPath), error: `read_failed: ${(err && err.message) || err}` });
      continue;
    }
    const { text, changed } = rewriteConfigText(original, mode);
    if (!changed) continue; // already in target mode — idempotent no-op, no restart
    try {
      // Write to a temp file in the same dir then rename for an atomic swap, so
      // a crash mid-write can never leave a half-written 3proxy config.
      const tmp = `${cfgPath}.egress.tmp`;
      await fsp.writeFile(tmp, text, "utf-8");
      await fsp.rename(tmp, cfgPath);
    } catch (err) {
      restartErrors.push({ cfg: path.basename(cfgPath), error: `write_failed: ${(err && err.message) || err}` });
      continue;
    }
    cfgsRewritten += 1;
    try {
      // Audit RES-11 — kill + respawn as one step of the shared process lock
      // (the supervisor never sees the batch "dead" in between).
      await withProcessLock(() => restartCfg(cfgPath));
    } catch (err) {
      restartErrors.push({ cfg: path.basename(cfgPath), error: `restart_failed: ${(err && err.message) || err}` });
    }
  }

  // `restarted` is true when every rewritten config was successfully restarted
  // (the contract's happy path). Per-cfg failures are surfaced in `errors`
  // without aborting the whole apply — the orchestrator collects per-node
  // ok/err and a partial restart still reports which configs need a retry.
  // ALWAYS persist the mode (even when nothing was rewritten — a fresh node or
  // idempotent re-apply must still record the current mode so the generation
  // contract follows it). A write failure does NOT abort: the cfg rewrites have
  // already happened, so it is reported in errors rather than thrown.
  try {
    persistEgressModeState(mode);
  } catch (err) {
    restartErrors.push({ cfg: "egress_mode.state", error: `state_write_failed: ${(err && err.message) || err}` });
  }

  const result = {
    ok: restartErrors.length === 0,
    mode,
    cfgs_rewritten: cfgsRewritten,
    restarted: restartErrors.length === 0,
  };
  if (restartErrors.length) {
    result.errors = restartErrors;
  }
  return result;
}

module.exports = {
  applyEgressMode,
  // Exposed for unit tests (pure rewrite logic, no fs / pgrep / spawn).
  rewriteConfigText,
  flagForMode,
  VALID_MODES,
  FLAG_FOR_MODE,
  EgressModeError,
  PROXY_CFG_DIR,
  // Egress-mode state persistence — read by server.js so the generation
  // contract follows the current toggle (bidirectional egress switch).
  EGRESS_MODE_STATE_PATH,
  readEgressModeState,
};
