"use strict";

// Pay-per-GB v2 — pergb_tag.js against the shared I3 fixture
// node_runtime/radius/tests/feistel_vectors.json (generated by an independent
// reference implementation; RADIUS's tag.py passes the same vectors).
// Run with: node --test node_runtime/node_agent/pergb_tag.test.js

const test = require("node:test");
const assert = require("node:assert");
const tag = require("./pergb_tag.js");
const fx = require("../radius/tests/feistel_vectors.json");

test("fixture format", () => {
  assert.strictEqual(fx.format, "netrun-pergb-feistel-v1");
  assert.ok(fx.vectors.length >= 50);
});

test("encrypt / decrypt / mac16 match every vector", () => {
  for (const v of fx.vectors) {
    const k = Buffer.from(v.keyB64, "base64");
    assert.strictEqual(tag.mac16(k, v.listId, v.r16), v.mac16, `mac16 ${v.listId}/${v.r16}`);
    const iid = tag.encrypt(k, v.listId, v.r16);
    assert.strictEqual(iid.toString(16).padStart(16, "0"), v.iid);
    assert.strictEqual(iid >= tag.IID_MIN, v.iidAccepted);
    const d = tag.decrypt(k, BigInt(`0x${v.iid}`));
    assert.deepStrictEqual(d, { listId: v.listId, r16: v.r16, valid: true });
  }
});

test("addresses: prefix | subnet << 64 | iid, and back", () => {
  for (const a of fx.addresses) {
    const t = tag.createTagger({ key: a.keyB64, prefix: a.prefix });
    assert.strictEqual(t.address(a.subnet, a.listId, a.r16), a.addr);
    const d = t.decodeAddress(a.addr);
    assert.strictEqual(d.subnetId, a.subnet);
    assert.strictEqual(d.listId, a.listId);
    assert.strictEqual(d.valid, true);
    assert.strictEqual(t.decodeAddress(`[${a.addr}]`).listId, a.listId, "bracketed");
  }
  const t = tag.createTagger({ key: fx.addresses[0].keyB64, prefix: fx.addresses[0].prefix });
  assert.strictEqual(t.decodeAddress("2001:db8:bb::1"), null, "outside the /48");
  assert.strictEqual(t.decodeAddress("203.0.113.5"), null);
});

test("invalid interface ids fail the MAC", () => {
  for (const v of fx.invalid) {
    const d = tag.decrypt(Buffer.from(v.keyB64, "base64"), BigInt(`0x${v.iid}`));
    assert.strictEqual(d.valid, v.tagValid);
    assert.strictEqual(d.listId, v.listId);
  }
});

test("ipv6 text <-> BigInt", () => {
  for (const s of ["2001:db8::1", "::", "2602:f2dc:a9:ffff::1", "::ffff:1.2.3.4", "2001:db8:aa:12:4301:2de4:e935:4ca7"]) {
    const b = tag.ipv6ToBig(s);
    assert.ok(b !== null, s);
    assert.strictEqual(tag.ipv6ToBig(tag.bigToIpv6(b)), b);
  }
  assert.strictEqual(tag.ipv6ToBig("fe80::1%eth0"), null);
  assert.strictEqual(tag.ipv6ToBig("1.2.3.4"), null);
  assert.strictEqual(tag.parsePrefix48("2602:F2DC:A9:12::5/48").text, "2602:f2dc:a9::/48");
  assert.strictEqual(tag.parsePrefix48("2602:f2dc:a9::/64"), null);
});
